# Generated by Django 5.1.6 on 2025-11-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalchat', '0002_group_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
