# Generated by Django 5.1.6 on 2025-11-08 05:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalchat', '0003_groupmessage_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='read',
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_group_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
